project_id = "ndgiuzknwptgppxqzkfe"

[functions.get-wallet-address]
verify_jwt = false

[functions.process-tip]
verify_jwt = false

[functions.neynar-webhook]
verify_jwt = false

[functions.get-cast-details]
verify_jwt = false

[functions.miniapp-webhook]
verify_jwt = false
